apiVersion: v1
kind: Service
metadata:
  name: cloudbees-pse-fixer
  labels:
    app.kubernetes.io/name: cloudbees-pse-fixer
    app.kubernetes.io/instance: {{ .Release.Name }}    
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app.kubernetes.io/name: cloudbees-pse-fixer
    app.kubernetes.io/instance: {{ .Release.Name }}    
