apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudbees-pse-fixer
  labels:
    app: cloudbees-pse-fixer
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudbees-pse-fixer
    spec:
      containers:
        - name: cloudbees-pse-fixer
          image: 783721547467.dkr.ecr.us-east-1.amazonaws.com/jenkins-executor-helpers:admc
          imagePullPolicy: Always
          args:
            - -webhookCfgFile=/etc/webhook/config/webhookConfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: cloudbees-pse-fixer-certs
        - name: webhook-config
          configMap:
            name: cloudbees-pse-fixer
