apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: cloudbees-pse-fixer
  labels:
    app: cloudbees-pse-fixer
webhooks:
  - name: cloudbees-pse-fixer.prezi.com
    clientConfig:
      service:
        name: cloudbees-pse-fixer
        namespace: cloudbees-pse-fixer
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]