resources:
    limits:
      cpu: 250m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - infra

nodeSelector:
  role: "infra"

tolerations:
  - key: "role"
    operator: "Equal"
    value: "infra"
    effect: "NoExecute"
