releases:
- name: cloudbees-fixer
  chart: "./cloudbees-fixer"
  version: 1.0
  namespace: "cloudbees-pse-fixer"
  installed: true
  values:
  # Ca bundle can be obtained from kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
  - ca_bundle.yaml
  - resources:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
